/**
 * This file was generated by the Jeddict
 */

package com.models;

import java.io.IOException;
import java.io.Serializable;
import java.io.StringWriter;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * @author simo-
 */

@Entity
public class Arret implements Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	@Basic
	private Double longueur;

	@Basic
	private Boolean oriente;
	//@JsonIgnore
	@ManyToOne(targetEntity = Sommet.class, cascade = { CascadeType.DETACH })
	private Sommet depart;
	//@JsonIgnore
	@ManyToOne(targetEntity = Sommet.class, cascade = { CascadeType.DETACH })
	private Sommet arrive;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Double getLongueur() {
		return this.longueur;
	}

	public void setLongueur(Double longueur) {
		this.longueur = longueur;
	}

	public Sommet getDepart() {
		return this.depart;
	}

	public void setDepart(Sommet depart) {
		this.depart = depart;
	}

	public Sommet getArrive() {
		return this.arrive;
	}

	public void setArrive(Sommet arrive) {
		this.arrive = arrive;
	}

	public Boolean isOriente() {
		return oriente;
	}

	public void setOriente(Boolean oriente) {
		this.oriente = oriente;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub

		ObjectMapper mapper = new ObjectMapper();
		StringWriter stringWriter = new StringWriter();
		try {
			mapper.writeValue(stringWriter, this);
		} catch (IOException e) {
			// TODO Auto-generated catch block

		}
		return stringWriter.toString();
	}

}
